"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_PRIORITY_OVER_SPREAD_OPTION = exports.DEFAULT_TARGET_CUSTOM_OPTION = exports.DEFAULT_TARGET_OPTION = void 0;
var DEFAULT_TARGET_OPTION = ['form'];
exports.DEFAULT_TARGET_OPTION = DEFAULT_TARGET_OPTION;
var DEFAULT_TARGET_CUSTOM_OPTION = [];
exports.DEFAULT_TARGET_CUSTOM_OPTION = DEFAULT_TARGET_CUSTOM_OPTION;
var DEFAULT_PRIORITY_OVER_SPREAD_OPTION = true;
exports.DEFAULT_PRIORITY_OVER_SPREAD_OPTION = DEFAULT_PRIORITY_OVER_SPREAD_OPTION;